namespace * org.burstsys.catalog.api

typedef i64 BurstCatalogApiKey
typedef i64 BurstTimestamp
typedef string BurstCatalogApiHostName
typedef string BurstCatalogApiHostAddress
typedef i32 BurstCatalogApiHostPort
typedef string BurstCatalogApiMoniker
typedef string BurstCatalogApiPropertyKey
typedef string BurstCatalogApiUdk
